# partition the disk, mbr, 1% free, 33% ntfs, 33% ext4, 33% ntfs
# create random user and encrypted password
# apt install ssh, wimtools, ntfs-3g, 7z-full
# get windows download script in browser
# scp windows preparation script
# run windows preparation script. needs work to make it batch install with the drivers.
# grub-reboot 1; reboot
