#cloud-config
autoinstall:
  apt:
    disable_components: []
    geoip: true
    preserve_sources_list: false
    primary:
    - arches:
      - amd64
      - i386
      uri: http://us.archive.ubuntu.com/ubuntu
    - arches:
      - default
      uri: http://ports.ubuntu.com/ubuntu-ports
  drivers:
    install: false
  identity:
    hostname: vmi939059
    password: $6$qWLwG2cJEh7mG5sw$8t94.hKJ870xeN4xIS07Ru2hrn1ACGnn9WkiL7kEpFxz7GgsLOnC2DgUvWgLswB95gqfjEa3AnGS6qSbCJEti0
    realname: adminov
    username: unmistames
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      ens18:
        dhcp4: true
    version: 2
  snaps:
  - channel: stable
    classic: true
    name: powershell
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  storage:
    config:
    - ptable: msdos
      serial: 0QEMU_QEMU_HARDDISK_drive-scsi0
      path: /dev/sda
      preserve: true
      name: ''
      grub_device: true
      type: disk
      id: disk-sda
    - device: disk-sda
      size: 85899345920
      wipe: superblock
      flag: boot
      number: 1
      preserve: true
      grub_device: false
      type: partition
      id: partition-sda1
    - fstype: ext4
      volume: partition-sda1
      preserve: false
      type: format
      id: format-0
    - path: /
      device: format-0
      type: mount
      id: mount-0
    - device: disk-sda
      size: 85899345920
      flag: boot
      number: 2
      preserve: true
      grub_device: false
      type: partition
      id: partition-sda2
    - device: disk-sda
      size: 128849018880
      flag: boot
      number: 3
      preserve: true
      grub_device: false
      type: partition
      id: partition-sda3
  updates: security
  version: 1
