#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Debian.4 net-install.iso" {
        insmod ext2
        set root='(hd0,2)'
        linux /linuxbabe/vmlinuz
        initrd /linuxbabe/initrd.gz
}
menuentry "preseed-debian-stable-amd64-netinst.iso" {
echo 1
set isofile="/root/preseed-debian-stable-amd64-netinst.iso"
loopback loop (hd0,msdos1)$isofile
linux (loop)/install.amd/vmlinuz boot=live components
splash quiet "${loopback}"
initrd (loop)/install.amd/initrd.gz
}
