#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Debian.4 net-install.iso" {
        insmod ext2
        set root='(hd0,2)'
        linux /linuxbabe/vmlinuz
        initrd /linuxbabe/initrd.gz
}
menuentry "Debian GNU/Linux 10.8.0 Live amd64" {
echo 1
set isofile="/debian/debian-live-10.8.0-amd64-lxde.iso"
loopback loop (hd0,gptx)$isofile
linux (loop)/live/vmlinuz-4.19.0-14-amd64 boot=live components
splash quiet "${loopback}"
initrd (loop)/live/initrd.img-4.19.0-14-amd64
}
