#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "ubuntu-jammy-autoinstall-2022-08-28.iso" {
  insmod ext2
  set isofile="/root/ubuntu-jammy-autoinstall-2022-08-28.iso"
  loopback loop (hd0,msdos1)$isofile
  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile quiet noeject noprompt splash
  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile autoinstall   ds=nocloud\;s=/cdrom/nocloud/  quiet noeject noprompt splash
  initrd (loop)/casper/initrd
}
